// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Friend_Button_Click_Success', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Friend_Button_Click_Success', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1028, height: 816 })
    await driver.wait(until.elementLocated(By.id("email")), 30000)
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("testuser1@uncw.edu")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("12345678")
    await driver.findElement(By.css(".MuiButtonBase-root")).click()
    await driver.sleep(2000)
    {
      assert(await driver.switchTo().alert().getText() == "Signed in as Test User")
      const element = await driver.findElement(By.css(".MuiButtonBase-root:nth-child(2) > .MuiBadge-root > .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(2) > .MuiBadge-root > .MuiSvgIcon-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.wait(until.elementLocated(By.css(".css-1lbclek-MuiGrid-root")), 30000)
    vars["url"] = await driver.executeScript("return window.location.href")
    assert(vars["url"].toString() == "http://localhost:5173/components/Friends")
  })
})
