// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Friend_Button_Click_Failed_Redirect', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Friend_Button_Click_Failed_Redirect', async function() {
    await driver.get("http://localhost:5173/")
    await driver.wait(until.elementLocated(By.css("h1")), 30000)
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("testuser1@uncw.edu")
    await driver.findElement(By.id("password")).sendKeys("12345678")
    await driver.findElement(By.css(".MuiButtonBase-root")).click()
    assert(await driver.switchTo().alert().getText() == "Signed in as Test User")
    await driver.manage().window().setRect({ width: 1026, height: 823 })
    {
      const elements = await driver.findElements(By.css(".css-1lbclek-MuiGrid-root"))
      assert(!elements.length)
    }
  })
})
