/* eslint-disable @typescript-eslint/no-var-requires */
// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Logging in', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Logging in', async function() {
    // Test name: Logging in
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:5173/")
    // 2 | setWindowSize | 1051x806 | 
    await driver.manage().window().setRect({ width: 1051, height: 806 })
    // 3 | click | id=email | 
    await driver.findElement(By.id("email")).click()
    // 4 | type | id=email | galindogaming@uncw.edu
    await driver.findElement(By.id("email")).sendKeys("galindogaming@uncw.edu")
    // 5 | click | id=password | 
    await driver.findElement(By.id("password")).click()
    // 6 | mouseOver | css=.MuiButtonBase-root | 
    {
      const element = await driver.findElement(By.css(".MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 7 | type | id=password | 12345678
    await driver.findElement(By.id("password")).sendKeys("12345678")
    // 8 | click | css=.MuiButtonBase-root | 
    await driver.findElement(By.css(".MuiButtonBase-root")).click()
    // 9 | assertAlert | Signed in as Octavio Galindo | 
    assert(await driver.switchTo().alert().getText() == "Signed in as Octavio Galindo")
    // 10 | click | css=.MuiIconButton-edgeEnd > .MuiSvgIcon-root | 
    await driver.findElement(By.css(".MuiIconButton-edgeEnd > .MuiSvgIcon-root")).click()
    // 11 | click | css=.MuiButton-contained | 
    await driver.findElement(By.css(".MuiButton-contained")).click()
  })
})
