// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Creating post', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Creating post', async function() {
    // Test name: Creating post
    // Automates creating a post on the forum
    // - assumes being logged in
    // Step # | name | target | value
    // 1 | open | /components/Forum | 
    await driver.get("http://localhost:5173/components/Forum")
    // 2 | setWindowSize | 550x699 | 
    await driver.manage().window().setRect({ width: 550, height: 699 })
    // 3 | click | id=:r3: | 
    await driver.findElement(By.id(":r3:")).click()
    // 4 | click | css=.MuiAutocomplete-popupIndicator > .MuiSvgIcon-root | 
    await driver.findElement(By.css(".MuiAutocomplete-popupIndicator > .MuiSvgIcon-root")).click()
    // 5 | type | id=:r3: | creating post - selenium
    await driver.findElement(By.id(":r3:")).sendKeys("creating post - selenium")
    // 6 | click | id=:r5:-option-1 | 
    await driver.findElement(By.id(":r5:-option-1")).click()
    // 7 | click | id=post-button-enabled | 
    await driver.findElement(By.id("post-button-enabled")).click()
    // 8 | mouseOver | css=.post-button-disabled | 
    {
      const element = await driver.findElement(By.css(".post-button-disabled"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
  })
})
