// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");
const mocha = require("mocha");

describe("Creating post", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("Creating post", async function () {
    await driver.get("http://localhost:5173/");
    await driver.sleep(3000);

    // Signing in...
    await driver.findElement(By.id("email")).click();
    await driver.findElement(By.id("email")).sendKeys("profiletest@uncw.edu");
    await driver.findElement(By.id("password")).sendKeys("test1234");
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER);
    await driver.sleep(3000);
    assert(
      (await driver.switchTo().alert().getText()) == "Signed in as Leon Kennedy"
    );
    await driver.switchTo().alert().accept();
    await driver.sleep(3000);

    // await driver.findElement(By.id(":r7:")).click();
    // await driver
    //   .findElement(By.css(".MuiAutocomplete-popupIndicator > .MuiSvgIcon-root"))
    //   .click();
    // await driver.findElement(By.id(":r7:")).click();
    await driver
      .findElement(By.id(":r7:"))
      .sendKeys("creating post - selenium");
    await driver.findElement(By.id(":r9:")).click();
    await driver
      .findElement(By.xpath("//*[contains(text(),'Crossword puzzles')]"))
      .click();
    // await driver.findElement(By.id(":r5-option-1:")).sendKeys("Music");
    await driver.findElement(By.id("post-button-enabled")).click();
    await driver.sleep(3000);
    assert(
      (await driver.findElement(By.className("post-description")).getText()) ==
        "creating post - selenium"
    );
  });
});
