// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Loading more posts', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Loading more posts', async function() {
    // Test name: Loading more posts
    // Step # | name | target | value
    // 1 | open | /components/Forum | 
    await driver.get("http://localhost:5173/components/Forum")
    // 2 | setWindowSize | 550x700 | 
    await driver.manage().window().setRect({ width: 550, height: 700 })
    // 3 | click | css=.load-more | 
    await driver.findElement(By.css(".load-more")).click()
  })
})
