// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("Login Tests", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("Bad email", async function () {
    await driver.get("http://localhost:5173");
    await driver.sleep(2000);
    await driver.findElement(By.id("email")).click();
    await driver.findElement(By.id("email")).sendKeys("notanemail");
    await driver.findElement(By.css(".MuiButtonBase-root")).click();
    assert(
      (await driver.findElement(By.id("email-helper-text")).getText()) ==
        "Email must include @"
    );
  });
  it("Bad password", async function () {
    await driver.get("http://localhost:5173");
    await driver.sleep(2000);
    await driver.findElement(By.id("email")).click();
    await driver.findElement(By.id("email")).sendKeys("test@test.com");
    await driver.findElement(By.css(".MuiButtonBase-root")).click();
    assert(
      (await driver.findElement(By.id("password-helper-text")).getText()) ==
        "Must fill out password"
    );
  });
  it("User not found", async function () {
    await driver.get("http://localhost:5173/");
    await driver.sleep(2000);
    await driver.findElement(By.id("email")).click();
    await driver.findElement(By.id("email")).sendKeys("test@bad.com");
    await driver.findElement(By.id("password")).sendKeys("12345678");
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER);
    await driver.sleep(2000);
    assert(
      (await driver.findElement(By.css(".errorMessage")).getText()) ==
        "User not found!"
    );
  });
  it("Valid user", async function () {
    await driver.get("http://localhost:5173/");
    await driver.sleep(2000);
    await driver.findElement(By.id("email")).click();
    await driver.findElement(By.id("email")).sendKeys("galindogaming@uncw.edu");
    await driver.findElement(By.id("password")).sendKeys("12345678");
    await driver.findElement(By.css(".MuiButtonBase-root")).click();
    await driver.sleep(2000);
    assert(
      (await driver.switchTo().alert().getText()) ==
        "Signed in as Octavio Galindo"
    );
    await driver.sleep(2000);
    await driver.switchTo().alert().accept();
  });
});
