// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('User not found', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('User not found', async function() {
    // Test name: User not found
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://csc-450-project.web.app/")
    // 2 | setWindowSize | 1752x940 | 
    await driver.manage().window().setRect({ width: 1752, height: 940 })
    // 3 | click | id=email | 
    await driver.findElement(By.id("email")).click()
    // 4 | type | id=email | test@bad.com
    await driver.findElement(By.id("email")).sendKeys("test@bad.com")
    // 5 | type | id=password | 12345678
    await driver.findElement(By.id("password")).sendKeys("12345678")
    // 6 | sendKeys | id=password | ${KEY_ENTER}
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    // 7 | assertText | css=.errorMessage | User not found!
    assert(await driver.findElement(By.css(".errorMessage")).getText() == "User not found!")
  })
})
