// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Change rating', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Change rating', async function() {
    // Test name: Change rating
    // Automates rating by upvoting, downvoting, and downvoting again
    // - the rating value at the end should be the same it was before
    // Step # | name | target | value
    // 1 | open | /components/Forum | 
    await driver.get("http://localhost:5173/components/Forum")
    // 2 | setWindowSize | 550x696 | 
    await driver.manage().window().setRect({ width: 550, height: 696 })
    // 3 | click | css=div:nth-child(2) > .MuiPaper-root .rating-button-container:nth-child(1) path | 
    await driver.findElement(By.css("div:nth-child(2) > .MuiPaper-root .rating-button-container:nth-child(1) path")).click()
    // 4 | click | css=div:nth-child(2) > .MuiPaper-root .rating-button-container:nth-child(3) .MuiSvgIcon-root | 
    await driver.findElement(By.css("div:nth-child(2) > .MuiPaper-root .rating-button-container:nth-child(3) .MuiSvgIcon-root")).click()
    // 5 | click | css=.rating-button-container:nth-child(3) .MuiSvgIcon-colorPrimary | 
    await driver.findElement(By.css(".rating-button-container:nth-child(3) .MuiSvgIcon-colorPrimary")).click()
    // 6 | close |  | 
    await driver.close()
  })
})
