// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

let driver;
let vars;
async function signIn() {
  await driver.get("http://localhost:5173");
  await driver.sleep(5000);
  await driver.findElement(By.id("email")).click();
  await driver
    .findElement(By.id("email"))
    .sendKeys("damon.incorvaia11@gmail.com");
  await driver.findElement(By.id("password")).click();
  await driver
    .findElement(By.id("password"))
    .sendKeys("totallysecurepassword" + Key.RETURN);
  await driver.sleep(3000);
  await driver.switchTo().alert().accept();
}

// Start of tests
describe("Edit Firstname to new name", function () {
  this.timeout(30000);
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("Edit Firstname to new name", async function () {
    await signIn();
    await driver.get("http://localhost:5173/components/Profile");
    await driver.sleep(5000);
    assert(
      (await driver.findElement(By.id("testing profile name")).getText()) ==
        "Damon Incorvaia"
    );
    await driver.findElement(By.css(".edit-button")).click();
    await driver.findElement(By.id(":r3:")).click();
    await driver.findElement(By.id(":r3:")).clear();
    await driver.findElement(By.id(":r3:")).sendKeys("Michael");
    await driver
      .findElement(By.css(".css-uln3b4-MuiButtonBase-root-MuiButton-root"))
      .click();
    await driver.sleep(2000);
    await driver.get("http://localhost:5173/components/Profile");
    await driver.sleep(2000);
    assert(
      (await driver.findElement(By.css(".profile-name")).getText()) ==
        "Michael Incorvaia"
    );
  });
});
